# Generated by Django 6.0.6 on 2026-06-15 20:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('file_name', models.CharField(help_text='Original file name including extension.', max_length=512)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes.')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('file', 'File'), ('code', 'Code')], default='file', max_length=32)),
                ('mime_type', models.CharField(help_text='MIME type (e.g. image/png, application/pdf).', max_length=127)),
                ('storage_key', models.CharField(help_text='S3/MinIO object key used to retrieve the file.', max_length=1024, unique=True)),
                ('url', models.URLField(blank=True, help_text='Pre-signed or public URL for direct access.', max_length=2048, null=True)),
                ('uploaded_by', models.UUIDField(help_text='identity.users.id of the user who uploaded this file.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary metadata (e.g. image dimensions, page count).')),
                ('knowledge_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='knowledge.knowledgespace')),
            ],
            options={
                'verbose_name': 'Knowledge Asset',
                'verbose_name_plural': 'Knowledge Assets',
                'db_table': 'knowledge_assets',
                'indexes': [models.Index(fields=['knowledge_space', 'file_type'], name='idx_ka_space_type'), models.Index(fields=['uploaded_by'], name='idx_ka_uploaded_by')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSpaceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version_number', models.PositiveIntegerField(help_text='Incremental version number within this knowledge space.')),
                ('canvas_snapshot', models.JSONField(help_text='Deep copy of canvas_data at this version.')),
                ('created_by', models.UUIDField(help_text='identity.users.id of the user who triggered this save.')),
                ('description', models.CharField(blank=True, help_text="Optional human-readable label (e.g. 'Added architecture diagram').", max_length=255, null=True)),
                ('knowledge_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.knowledgespace')),
            ],
            options={
                'verbose_name': 'Knowledge Space Version',
                'verbose_name_plural': 'Knowledge Space Versions',
                'db_table': 'knowledge_space_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['knowledge_space', '-version_number'], name='idx_ksv_version_desc')],
                'constraints': [models.UniqueConstraint(fields=('knowledge_space', 'version_number'), name='uq_ksv_version')],
            },
        ),
    ]
