# Generated by Django 5.2.14 on 2026-05-15 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'revoked', 'expires_at'], name='auth_refres_user_id_c0d4c2_idx'),
        ),
    ]
