from django.urls import path

from apps.projects.views import (
    ProjectAIRecommendationsView,
    ProjectDetailView,
    ProjectListView,
    ProjectTaskListView,
    TaskDependencyDestroyView,
    TaskDependencyView,
    TaskDetailView,
    TaskListView,
    TaskStatusUpdateView,
)

urlpatterns = [
    path(
        "workspaces/<uuid:workspace_pk>/projects/",
        ProjectListView.as_view(),
        name="project-list-create",
    ),
    path(
        "workspaces/<uuid:workspace_pk>/projects/<uuid:project_id>/",
        ProjectDetailView.as_view(),
        name="project-detail",
    ),
    path(
        "workspaces/<uuid:workspace_pk>/projects/<uuid:project_id>/tasks/",
        ProjectTaskListView.as_view(),
        name="project-task-list",
    ),
    path(
        "workspaces/<uuid:workspace_pk>/projects/<uuid:project_id>/ai/recommendations/",
        ProjectAIRecommendationsView.as_view(),
        name="project-ai-recommendations",
    ),
    path(
        "workspaces/<uuid:workspace_pk>/tasks/",
        TaskListView.as_view(),
        name="task-list-create",
    ),
    path(
        "workspaces/<uuid:workspace_pk>/tasks/<uuid:task_id>/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "workspaces/<uuid:workspace_pk>/tasks/<uuid:task_id>/status/",
        TaskStatusUpdateView.as_view(),
        name="task-status-update",
    ),
    path(
        "workspaces/<uuid:workspace_pk>/tasks/<uuid:task_id>/dependencies/",
        TaskDependencyView.as_view(),
        name="task-dependency-create",
    ),
    path(
        "workspaces/<uuid:workspace_pk>/tasks/<uuid:task_id>/dependencies/<uuid:dependency_id>/",
        TaskDependencyDestroyView.as_view(),
        name="task-dependency-destroy",
    ),
]
