# Generated by Django 5.2.14 on 2026-06-17 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workspace_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(max_length=20000)),
                ("author_id", models.UUIDField(db_index=True)),
                ("author_username", models.CharField(max_length=50)),
                ("author_display_name", models.CharField(max_length=120)),
                ("author_avatar_url", models.URLField(blank=True, default="")),
                ("upvote_count", models.IntegerField(db_index=True, default=0)),
                ("downvote_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "community_discussions"},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("usage_count", models.IntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "community_tags",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(max_length=5000)),
                ("author_id", models.UUIDField(db_index=True)),
                ("author_username", models.CharField(max_length=50)),
                ("author_display_name", models.CharField(max_length=120)),
                ("author_avatar_url", models.URLField(blank=True, default="")),
                ("upvote_count", models.IntegerField(default=0)),
                ("downvote_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="community.comment",
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="community.discussion",
                    ),
                ),
            ],
            options={"db_table": "community_comments"},
        ),
        migrations.AddField(
            model_name="discussion",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="discussions", to="community.tag"
            ),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "value",
                    models.SmallIntegerField(choices=[(1, "Upvote"), (-1, "Downvote")]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="community.comment",
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="community.discussion",
                    ),
                ),
            ],
            options={"db_table": "community_votes"},
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["discussion", "-created_at"], name="comment_disc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent", "-created_at"], name="comment_parent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(fields=["-created_at"], name="disc_created_idx"),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(fields=["-upvote_count"], name="disc_upvote_idx"),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["-upvote_count", "-created_at"], name="disc_trending_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["is_pinned", "-created_at"], name="disc_pinned_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["user_id", "discussion"], name="vote_user_disc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["user_id", "comment"], name="vote_user_comment_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("comment__isnull", True), ("discussion__isnull", False)),
                    models.Q(("comment__isnull", False), ("discussion__isnull", True)),
                    _connector="OR",
                ),
                name="vote_single_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("user_id", "discussion"), name="unique_discussion_vote"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("user_id", "comment"), name="unique_comment_vote"
            ),
        ),
    ]
