# Generated by Django 5.2.14 on 2026-06-06 06:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("workspaces", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace General"),
                            ("group", "Group Chat"),
                            ("ai", "AI Thread"),
                            ("dm", "Direct Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_by", models.UUIDField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Room",
                "verbose_name_plural": "Chat Rooms",
                "db_table": "chat_rooms",
                "indexes": [
                    models.Index(
                        fields=["workspace", "room_type"],
                        name="chat_rooms_workspa_657517_idx",
                    )
                ],
            },
        )
    ]
