# Generated by Django 5.2.14 on 2026-06-20 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0004_add_chat_room_participant_and_last_message_fields")]

    operations = [
        migrations.RenameIndex(
            model_name="chatroomparticipant",
            new_name="chat_room_p_user_id_94d4ce_idx",
            old_name="chat_room_pa_user_id_2376ee_idx",
        ),
        migrations.AlterField(
            model_name="chatroomparticipant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
