# Generated by Django 5.2.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0005_rename_chat_room_pa_user_id_2376ee_idx_chat_room_p_user_id_94d4ce_idx_and_more")]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="message_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatroomparticipant",
            name="last_read_message_count",
            field=models.IntegerField(default=0),
        ),
    ]
