# Generated by Django 6.0.5 on 2026-07-09 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_add_message_count_and_last_read"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("DM", "Direct Message"),
                            ("GROUP", "Group Chat"),
                            ("WORKSPACE_TEAM", "Workspace Team"),
                            ("AI_CHAT", "AI Chat"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_by", models.UUIDField()),
                ("member_count", models.IntegerField(default=1)),
                ("message_count", models.IntegerField(default=0)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_content", models.TextField(blank=True, default="")),
                (
                    "last_message_sender_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only set for WORKSPACE_TEAM — all other types are workspace-agnostic.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_group",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat V2 Room",
                "verbose_name_plural": "Chat V2 Rooms",
                "db_table": "chat_v2_rooms",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#9898a6", max_length=7)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("can_delete_messages", models.BooleanField(default=False)),
                ("can_pin_messages", models.BooleanField(default=False)),
                ("can_manage_members", models.BooleanField(default=False)),
                ("can_manage_roles", models.BooleanField(default=False)),
                ("can_share_repositories", models.BooleanField(default=False)),
                ("can_view_audit_logs", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v2_roles",
                        to="chat.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat V2 Role",
                "verbose_name_plural": "Chat V2 Roles",
                "db_table": "chat_v2_roles",
            },
        ),
        migrations.CreateModel(
            name="PinnedMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("message_seq", models.BigIntegerField()),
                ("pinned_by", models.UUIDField()),
                ("pinned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v2_pinned_messages",
                        to="chat.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat V2 Pinned Message",
                "verbose_name_plural": "Chat V2 Pinned Messages",
                "db_table": "chat_v2_pinned_messages",
            },
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("user_id", models.UUIDField()),
                ("content", models.TextField(blank=True, default="")),
                ("reply_to_seq", models.BigIntegerField(blank=True, null=True)),
                ("attachment_urls", models.JSONField(blank=True, default=list)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v2_drafts",
                        to="chat.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat V2 Draft",
                "verbose_name_plural": "Chat V2 Drafts",
                "db_table": "chat_v2_drafts",
            },
        ),
        migrations.CreateModel(
            name="RoomInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("target_user_id", models.UUIDField()),
                ("invited_by_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v2_invites",
                        to="chat.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat V2 Room Invite",
                "verbose_name_plural": "Chat V2 Room Invites",
                "db_table": "chat_v2_room_invites",
            },
        ),
        migrations.CreateModel(
            name="RoomMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("user_id", models.UUIDField()),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_seq", models.BigIntegerField(default=0)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v2_members",
                        to="chat.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat V2 Room Member",
                "verbose_name_plural": "Chat V2 Room Members",
                "db_table": "chat_v2_room_members",
            },
        ),
        migrations.CreateModel(
            name="RoomMemberRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v2_roles",
                        to="chat.roommember",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.role"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat V2 Member Role",
                "verbose_name_plural": "Chat V2 Member Roles",
                "db_table": "chat_v2_member_roles",
            },
        ),
        migrations.CreateModel(
            name="ScheduledMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("sender_id", models.UUIDField()),
                ("content", models.TextField()),
                ("send_at", models.DateTimeField(db_index=True)),
                ("is_sent", models.BooleanField(db_index=True, default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v2_scheduled_messages",
                        to="chat.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat V2 Scheduled Message",
                "verbose_name_plural": "Chat V2 Scheduled Messages",
                "db_table": "chat_v2_scheduled_messages",
            },
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["room_type", "-last_message_at"], name="idx_v2_room_type_recent"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["workspace"], name="idx_v2_room_workspace"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["created_by"], name="idx_v2_room_creator"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["is_public", "room_type"], name="idx_v2_room_public_type"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["room", "priority"], name="idx_v2_role_room_priority"
            ),
        ),
        migrations.AddIndex(
            model_name="pinnedmessage",
            index=models.Index(
                fields=["room", "-pinned_at"], name="idx_v2_pinned_room_recent"
            ),
        ),
        migrations.AddIndex(
            model_name="draft",
            index=models.Index(
                fields=["room", "user_id"], name="idx_v2_draft_room_user"
            ),
        ),
        migrations.AddIndex(
            model_name="roominvite",
            index=models.Index(
                fields=["target_user_id", "status"], name="idx_v2_invite_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="roommember",
            index=models.Index(
                fields=["user_id", "room"], name="idx_v2_member_user_room"
            ),
        ),
        migrations.AddIndex(
            model_name="roommember",
            index=models.Index(
                fields=["user_id", "-joined_at"], name="idx_v2_member_user_recent"
            ),
        ),
        migrations.AddConstraint(
            model_name="roommember",
            constraint=models.UniqueConstraint(
                fields=("room", "user_id"), name="uq_v2_room_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="roommemberrole",
            constraint=models.UniqueConstraint(
                fields=("member", "role"), name="uq_v2_member_role"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledmessage",
            index=models.Index(
                fields=["send_at", "is_sent"], name="idx_v2_scheduled_pending"
            ),
        ),
    ]
