# Generated by Django 5.2.14 on 2026-06-02 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('github_repo', models.CharField(db_index=True, help_text="GitHub repository in 'owner/repo' format (e.g. 'acme/api'). Updated automatically when metadata is refreshed.", max_length=255)),
                ('github_id', models.BigIntegerField(db_index=True, help_text='Stable GitHub repository ID. Does not change on rename or transfer.')),
                ('default_branch', models.CharField(default='main', help_text='Default branch name as reported by GitHub.', max_length=255)),
                ('language', models.CharField(blank=True, help_text='Primary programming language as reported by GitHub. Null if not detected.', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Repository description from GitHub. Truncated at 500 characters.', max_length=500, null=True)),
                ('is_private', models.BooleanField(default=False, help_text='Whether the GitHub repository is private.')),
                ('last_analyzed_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the last completed analysis run by the Analysis Service.', null=True)),
                ('last_analysis_score', models.DecimalField(blank=True, decimal_places=2, help_text='Aggregate score (0.00–100.00) from the last analysis run.', max_digits=5, null=True)),
                ('indexed', models.BooleanField(db_index=True, default=False, help_text='Whether the repository has been indexed for AI/RAG search by the AI Service.')),
                ('connected_by_id', models.UUIDField(blank=True, help_text='identity.users.id of the user who connected the repository. Audit trail.', null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'repositories',
                'indexes': [models.Index(fields=['workspace', 'deleted_at'], name='idx_repos_workspace_active'), models.Index(fields=['workspace', 'github_repo'], name='idx_workspace_github_repo')],
                'unique_together': {('workspace', 'github_id')},
            },
        ),
    ]
