# Generated by Django 5.2.14 on 2026-06-10 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("repositories", "0002_github_app_models")]

    operations = [
        migrations.RenameIndex(
            model_name="githubappinstallation",
            new_name="idx_gh_install_ws_active",
            old_name="idx_gh_install_workspace_active",
        )
    ]
